/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IMdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    IMdiArrowTopRightThick: typeof import('~icons/mdi/arrow-top-right-thick')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IMdiMastodon: typeof import('~icons/mdi/mastodon')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
